version: "3.9"
services:
  web:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: bash -lc "cd apps/web && npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=http://localhost:54321
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=dev-placeholder
    depends_on:
      - ai

  ai:
    build:
      context: ./services/ai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1


